import { useEffect, useMemo, useState } from "react";
import type { MarketCatalogItem, MarketSettings as MarketSettingsData } from "../types";
import { api } from "../api";
import { Badge, Card, ErrorNote } from "./Ui";

const GROUPS: { key: MarketCatalogItem["assetClass"]; title: string; note?: string }[] = [
  { key: "Forex", title: "Forex" },
  {
    key: "SyntheticIndex",
    title: "Derived (synthetic indices)",
    note: "Generated by Deriv's random number generator: there is no real market behind them, so strategies cannot have an edge and every trade pays commission. Use for experimentation only.",
  },
  { key: "StockIndex", title: "Stock indices", note: "Deriv offers no multiplier contracts on these through the API: they are analysed and journaled, never traded." },
  { key: "Commodity", title: "Commodities" },
  { key: "Crypto", title: "Crypto" },
];

export function MarketSettings() {
  const [data, setData] = useState<MarketSettingsData | null>(null);
  const [selected, setSelected] = useState<Set<string>>(new Set());
  const [filter, setFilter] = useState("");
  const [tradableOnly, setTradableOnly] = useState(false);
  const [derivedOnlyWhenForexClosed, setDerivedOnlyWhenForexClosed] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [saving, setSaving] = useState(false);

  const load = async (resetSelection: boolean) => {
    try {
      const d = await api.get<MarketSettingsData>("/api/settings/markets");
      setData(d);
      if (resetSelection) {
        setSelected(new Set(d.selected));
        setDerivedOnlyWhenForexClosed(d.derivedOnlyWhenForexClosed);
      }
      setError(null);
    } catch (e) {
      setError((e as Error).message);
    }
  };

  useEffect(() => {
    void load(true);
  }, []);

  const pending = !!data && data.version !== data.appliedVersion && data.version > 0;
  useEffect(() => {
    if (!pending) return;
    const id = window.setInterval(() => void load(false), 5000);
    return () => window.clearInterval(id);
  }, [pending]);

  const dirty = useMemo(() => {
    if (!data) return false;
    const current = new Set(data.selected);
    return (
      current.size !== selected.size ||
      [...selected].some((s) => !current.has(s)) ||
      derivedOnlyWhenForexClosed !== data.derivedOnlyWhenForexClosed
    );
  }, [data, selected, derivedOnlyWhenForexClosed]);

  const toggle = (symbol: string) =>
    setSelected((prev) => {
      const next = new Set(prev);
      if (next.has(symbol)) next.delete(symbol);
      else next.add(symbol);
      return next;
    });

  const save = async () => {
    setSaving(true);
    setError(null);
    try {
      const d = await api.put<MarketSettingsData>("/api/settings/markets", { instruments: [...selected], derivedOnlyWhenForexClosed });
      setData(d);
      setSelected(new Set(d.selected));
      setDerivedOnlyWhenForexClosed(d.derivedOnlyWhenForexClosed);
    } catch (e) {
      setError((e as Error).message);
    } finally {
      setSaving(false);
    }
  };

  const q = filter.trim().toLowerCase();
  const catalog = data?.catalog ?? [];
  const visible = catalog.filter(
    (m) =>
      (!tradableOnly || m.isTradable) &&
      (!q || m.name.toLowerCase().includes(q) || m.symbol.toLowerCase().includes(q) || m.submarket.toLowerCase().includes(q)),
  );
  const byName = new Map(catalog.map((m) => [m.symbol, m]));

  return (
    <div className="stack">
      <Card title={`Selected markets (${selected.size}/${data?.maxSelected ?? 30})`}>
        {selected.size === 0 ? (
          <p className="empty">Nothing selected — pick at least one market below.</p>
        ) : (
          <div className="chips">
            {[...selected].map((symbol) => (
              <span key={symbol} className="chip removable">
                {byName.get(symbol)?.name ?? symbol}
                <button aria-label={`Remove ${symbol}`} onClick={() => toggle(symbol)}>×</button>
              </span>
            ))}
          </div>
        )}
        <label className="event-option" style={{ marginTop: 14 }}>
          <input type="checkbox" checked={derivedOnlyWhenForexClosed} onChange={(e) => setDerivedOnlyWhenForexClosed(e.target.checked)} />
          <span>
            <span className="strong">Trade Derived markets only while Forex is closed</span>
            <span className="muted small">
              {" "}— while Forex trades, evaluations and position slots go to Forex; on weekends and during the daily break the selected Derived
              markets take over.
            </span>
          </span>
        </label>
        <div className="form-actions" style={{ marginTop: 12 }}>
          <button className="primary" onClick={save} disabled={saving || !dirty || selected.size === 0}>
            {saving ? "Saving…" : "Save selection"}
          </button>
          {dirty && (
            <button
              onClick={() => {
                if (!data) return;
                setSelected(new Set(data.selected));
                setDerivedOnlyWhenForexClosed(data.derivedOnlyWhenForexClosed);
              }}
            >
              Discard changes
            </button>
          )}
          {pending ? (
            <Badge tone="warn">restarting worker to apply…</Badge>
          ) : (
            data && !dirty && <span className="muted small">{data.isDefaultSelection ? "Using the default Forex majors." : "Applied."}</span>
          )}
          {dirty && <span className="muted small">Unsaved changes. Saving restarts the worker (about a minute to reload history).</span>}
        </div>
        <ErrorNote error={error} />
      </Card>

      <Card
        title="Available markets"
        actions={
          <div className="toolbar">
            <label className="check">
              <input type="checkbox" checked={tradableOnly} onChange={(e) => setTradableOnly(e.target.checked)} /> tradable only
            </label>
            <input className="search" placeholder="Search…" value={filter} onChange={(e) => setFilter(e.target.value)} />
          </div>
        }
      >
        {catalog.length === 0 && <p className="empty">The market catalog appears once the worker has started with Deriv market data.</p>}
        {GROUPS.map((group) => {
          const items = visible.filter((m) => m.assetClass === group.key);
          if (items.length === 0) return null;
          const chosen = items.filter((m) => selected.has(m.symbol)).length;
          return (
            <details key={`${group.key}-${q}`} className="market-group" open={!!q || chosen > 0}>
              <summary>
                <span className="strong">{group.title}</span>
                <span className="muted small"> · {items.length} markets{chosen > 0 ? ` · ${chosen} selected` : ""}</span>
              </summary>
              {group.note && <p className={`hint small ${group.key === "SyntheticIndex" ? "warn-text" : ""}`}>{group.note}</p>}
              <div className="market-grid">
                {items.map((m) => (
                  <label key={m.brokerSymbol} className={`market-option ${selected.has(m.symbol) ? "checked" : ""}`}>
                    <input type="checkbox" checked={selected.has(m.symbol)} onChange={() => toggle(m.symbol)} />
                    <span className="market-name">{m.name}</span>
                    <span className="market-meta">
                      {[m.name !== m.symbol ? m.symbol : null, m.isTradable ? null : "analysis only", m.isOpen ? null : "closed"]
                        .filter(Boolean)
                        .join(" · ") || "tradable"}
                    </span>
                  </label>
                ))}
              </div>
            </details>
          );
        })}
      </Card>
    </div>
  );
}
