import { useEffect, useMemo, useState } from "react";
import type { MarketCatalogItem, MarketSettings as MarketSettingsData } from "../types";
import { api } from "../api";
import { Badge, Card, ErrorNote } from "./Ui";

const GROUPS: { key: MarketCatalogItem["assetClass"]; title: string; note?: string }[] = [
  { key: "Forex", title: "Forex" },
  {
    key: "SyntheticIndex",
    title: "Derived (synthetic indices)",
    note: "Generated by Deriv's random number generator: there is no real market behind them, so strategies cannot have an edge and every trade pays commission. Use for experimentation only.",
  },
  { key: "StockIndex", title: "Stock indices", note: "Deriv offers no multiplier contracts on these through the API: they are analysed and journaled, never traded." },
  { key: "Commodity", title: "Commodities" },
  { key: "Crypto", title: "Crypto" },
];

export function MarketSettings() {
  const [data, setData] = useState<MarketSettingsData | null>(null);
  const [selected, setSelected] = useState<Set<string>>(new Set());
  const [filter, setFilter] = useState("");
  const [error, setError] = useState<string | null>(null);
  const [saving, setSaving] = useState(false);

  const load = async (resetSelection: boolean) => {
    try {
      const d = await api.get<MarketSettingsData>("/api/settings/markets");
      setData(d);
      if (resetSelection) setSelected(new Set(d.selected));
      setError(null);
    } catch (e) {
      setError((e as Error).message);
    }
  };

  useEffect(() => {
    void load(true);
  }, []);

  const pending = !!data && data.version !== data.appliedVersion && data.version > 0;
  useEffect(() => {
    if (!pending) return;
    const id = window.setInterval(() => void load(false), 5000);
    return () => window.clearInterval(id);
  }, [pending]);

  const dirty = useMemo(() => {
    if (!data) return false;
    const current = new Set(data.selected);
    return current.size !== selected.size || [...selected].some((s) => !current.has(s));
  }, [data, selected]);

  const toggle = (symbol: string) =>
    setSelected((prev) => {
      const next = new Set(prev);
      if (next.has(symbol)) next.delete(symbol);
      else next.add(symbol);
      return next;
    });

  const save = async () => {
    setSaving(true);
    setError(null);
    try {
      const d = await api.put<MarketSettingsData>("/api/settings/markets", { instruments: [...selected] });
      setData(d);
      setSelected(new Set(d.selected));
    } catch (e) {
      setError((e as Error).message);
    } finally {
      setSaving(false);
    }
  };

  const q = filter.trim().toLowerCase();
  const visible = (data?.catalog ?? []).filter(
    (m) => !q || m.name.toLowerCase().includes(q) || m.symbol.toLowerCase().includes(q) || m.submarket.toLowerCase().includes(q),
  );

  return (
    <Card
      title="Markets"
      actions={<input className="search" placeholder="Search markets…" value={filter} onChange={(e) => setFilter(e.target.value)} />}
    >
      <p className="hint">
        Choose what the engine analyses and trades (max {data?.maxSelected ?? 30}). Saving restarts the trading worker, which reloads 45 days of
        history per market; open positions stay protected by their broker-side stop loss and take profit.
      </p>
      {data && data.catalog.length === 0 && (
        <p className="empty">The market catalog appears once the worker has started with Deriv market data.</p>
      )}
      {GROUPS.map((group) => {
        const items = visible.filter((m) => m.assetClass === group.key);
        if (items.length === 0) return null;
        return (
          <div key={group.key} className="market-group">
            <h3>
              {group.title} <span className="muted small">{items.filter((m) => selected.has(m.symbol)).length} selected</span>
            </h3>
            {group.note && <p className={`hint small ${group.key === "SyntheticIndex" ? "warn-text" : ""}`}>{group.note}</p>}
            <div className="market-grid">
              {items.map((m) => (
                <label key={m.brokerSymbol} className={`market-option ${selected.has(m.symbol) ? "checked" : ""}`}>
                  <input type="checkbox" checked={selected.has(m.symbol)} onChange={() => toggle(m.symbol)} />
                  <span className="market-name">{m.name}</span>
                  <span className="market-meta">
                    {m.symbol}
                    {m.isTradable ? ` · x${m.multipliers[0]}–${m.multipliers[m.multipliers.length - 1]}` : ""}
                  </span>
                  <span className="market-badges">
                    {!m.isTradable && <Badge tone="neutral">analysis only</Badge>}
                    <Badge tone={m.isOpen ? "good" : "neutral"}>{m.isOpen ? "open" : "closed"}</Badge>
                  </span>
                </label>
              ))}
            </div>
          </div>
        );
      })}
      <div className="form-actions" style={{ marginTop: 12 }}>
        <button className="primary" onClick={save} disabled={saving || !dirty || selected.size === 0}>
          {saving ? "Saving…" : `Save selection (${selected.size})`}
        </button>
        {dirty && <button onClick={() => data && setSelected(new Set(data.selected))}>Discard changes</button>}
        {pending ? (
          <Badge tone="warn">restarting worker to apply…</Badge>
        ) : (
          data && <span className="muted small">{data.isDefaultSelection ? "Using the default Forex majors." : "Applied."}</span>
        )}
      </div>
      <ErrorNote error={error} />
    </Card>
  );
}
