// <auto-generated />
using System;
using HVTradingBot.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HVTradingBot.Infrastructure.Sqlite.Migrations
{
    [DbContext(typeof(TradingDbContext))]
    partial class TradingDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("HVTradingBot.Infrastructure.Persistence.Entities.AppUserEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at_utc");

                    b.Property<int>("FailedLogins")
                        .HasColumnType("INTEGER")
                        .HasColumnName("failed_logins");

                    b.Property<DateTime?>("LastLoginAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_login_at_utc");

                    b.Property<DateTime?>("LockedUntilUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("locked_until_utc");

                    b.Property<DateTime?>("PasswordChangedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("password_changed_at_utc");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT")
                        .HasColumnName("password_hash");

                    b.Property<string>("SecurityStamp")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("security_stamp");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("pk_app_users");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasDatabaseName("ix_app_users_username");

                    b.ToTable("app_users", (string)null);
                });

            modelBuilder.Entity("HVTradingBot.Infrastructure.Persistence.Entities.AuditLogEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("action");

                    b.Property<string>("Actor")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("actor");

                    b.Property<string>("CorrelationId")
                        .HasColumnType("TEXT")
                        .HasColumnName("correlation_id");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT")
                        .HasColumnName("details");

                    b.Property<DateTime>("TimestampUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("timestamp_utc");

                    b.HasKey("Id")
                        .HasName("pk_audit_logs");

                    b.HasIndex("TimestampUtc")
                        .HasDatabaseName("ix_audit_logs_timestamp_utc");

                    b.ToTable("audit_logs", (string)null);
                });

            modelBuilder.Entity("HVTradingBot.Infrastructure.Persistence.Entities.BacktestRunEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at_utc");

                    b.Property<double>("NetPnl")
                        .HasPrecision(28, 10)
                        .HasColumnType("REAL")
                        .HasColumnName("net_pnl");

                    b.Property<string>("Parameters")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("parameters");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("source");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("summary");

                    b.Property<int>("TotalTrades")
                        .HasColumnType("INTEGER")
                        .HasColumnName("total_trades");

                    b.HasKey("Id")
                        .HasName("pk_backtest_runs");

                    b.HasIndex("CreatedAtUtc")
                        .HasDatabaseName("ix_backtest_runs_created_at_utc");

                    b.ToTable("backtest_runs", (string)null);
                });

            modelBuilder.Entity("HVTradingBot.Infrastructure.Persistence.Entities.BrokerAccountEntity", b =>
                {
                    b.Property<string>("AccountKey")
                        .HasColumnType("TEXT")
                        .HasColumnName("account_key");

                    b.Property<string>("Broker")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("broker");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("currency");

                    b.Property<bool>("IsDemo")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_demo");

                    b.Property<double>("LastBalance")
                        .HasPrecision(28, 10)
                        .HasColumnType("REAL")
                        .HasColumnName("last_balance");

                    b.Property<double>("StartingBalance")
                        .HasPrecision(28, 10)
                        .HasColumnType("REAL")
                        .HasColumnName("starting_balance");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("AccountKey")
                        .HasName("pk_broker_accounts");

                    b.ToTable("broker_accounts", (string)null);
                });

            modelBuilder.Entity("HVTradingBot.Infrastructure.Persistence.Entities.BrokerConnectionStatusEntity", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("AccountsJson")
                        .HasColumnType("TEXT")
                        .HasColumnName("accounts_json");

                    b.Property<DateTime>("CheckedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("checked_at_utc");

                    b.Property<string>("ConnectedAccountId")
                        .HasColumnType("TEXT")
                        .HasColumnName("connected_account_id");

                    b.Property<string>("Message")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT")
                        .HasColumnName("message");

                    b.Property<int>("SettingsVersion")
                        .HasColumnType("INTEGER")
                        .HasColumnName("settings_version");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_broker_connection_status");

                    b.ToTable("broker_connection_status", (string)null);
                });

            modelBuilder.Entity("HVTradingBot.Infrastructure.Persistence.Entities.BrokerSettingsEntity", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("DerivAccountId")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasColumnName("deriv_account_id");

                    b.Property<string>("DerivApiTokenHint")
                        .HasMaxLength(8)
                        .HasColumnType("TEXT")
                        .HasColumnName("deriv_api_token_hint");

                    b.Property<string>("DerivApiTokenProtected")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT")
                        .HasColumnName("deriv_api_token_protected");

                    b.Property<string>("DerivAppId")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("deriv_app_id");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at_utc");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_by");

                    b.Property<int>("Version")
                        .HasColumnType("INTEGER")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_broker_settings");

                    b.ToTable("broker_settings", (string)null);
                });

            modelBuilder.Entity("HVTradingBot.Infrastructure.Persistence.Entities.CandleEntity", b =>
                {
                    b.Property<string>("Instrument")
                        .HasMaxLength(16)
                        .HasColumnType("TEXT")
                        .HasColumnName("instrument");

                    b.Property<string>("TimeFrame")
                        .HasMaxLength(8)
                        .HasColumnType("TEXT")
                        .HasColumnName("time_frame");

                    b.Property<DateTime>("OpenTimeUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("open_time_utc");

                    b.Property<double>("Close")
                        .HasPrecision(28, 10)
                        .HasColumnType("REAL")
                        .HasColumnName("close");

                    b.Property<double>("High")
                        .HasPrecision(28, 10)
                        .HasColumnType("REAL")
                        .HasColumnName("high");

                    b.Property<double>("Low")
                        .HasPrecision(28, 10)
                        .HasColumnType("REAL")
                        .HasColumnName("low");

                    b.Property<double>("Open")
                        .HasPrecision(28, 10)
                        .HasColumnType("REAL")
                        .HasColumnName("open");

                    b.Property<double>("Spread")
                        .HasPrecision(28, 10)
                        .HasColumnType("REAL")
                        .HasColumnName("spread");

                    b.Property<long>("Volume")
                        .HasColumnType("INTEGER")
                        .HasColumnName("volume");

                    b.HasKey("Instrument", "TimeFrame", "OpenTimeUtc")
                        .HasName("pk_candles");

                    b.ToTable("candles", (string)null);
                });

            modelBuilder.Entity("HVTradingBot.Infrastructure.Persistence.Entities.CloseRequestEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("completed_at_utc");

                    b.Property<double?>("ExitPrice")
                        .HasPrecision(28, 10)
                        .HasColumnType("REAL")
                        .HasColumnName("exit_price");

                    b.Property<string>("Instrument")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasColumnName("instrument");

                    b.Property<string>("Message")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT")
                        .HasColumnName("message");

                    b.Property<Guid>("PositionId")
                        .HasColumnType("TEXT")
                        .HasColumnName("position_id");

                    b.Property<double?>("RealizedPnl")
                        .HasPrecision(28, 10)
                        .HasColumnType("REAL")
                        .HasColumnName("realized_pnl");

                    b.Property<DateTime>("RequestedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("requested_at_utc");

                    b.Property<string>("RequestedBy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("requested_by");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_close_requests");

                    b.HasIndex("PositionId", "Status")
                        .HasDatabaseName("ix_close_requests_position_id_status");

                    b.ToTable("close_requests", (string)null);
                });

            modelBuilder.Entity("HVTradingBot.Infrastructure.Persistence.Entities.MarketEntity", b =>
                {
                    b.Property<string>("BrokerSymbol")
                        .HasColumnType("TEXT")
                        .HasColumnName("broker_symbol");

                    b.Property<string>("AssetClass")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("asset_class");

                    b.Property<string>("BaseCurrency")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("base_currency");

                    b.Property<bool>("IsOpen")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_open");

                    b.Property<bool>("IsTradable")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_tradable");

                    b.Property<string>("Market")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("market");

                    b.Property<string>("Multipliers")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("multipliers");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<double>("PipSize")
                        .HasPrecision(28, 10)
                        .HasColumnType("REAL")
                        .HasColumnName("pip_size");

                    b.Property<int>("PriceDecimals")
                        .HasColumnType("INTEGER")
                        .HasColumnName("price_decimals");

                    b.Property<string>("QuoteCurrency")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("quote_currency");

                    b.Property<string>("Submarket")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("submarket");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("symbol");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("BrokerSymbol")
                        .HasName("pk_markets");

                    b.HasIndex("Symbol")
                        .IsUnique()
                        .HasDatabaseName("ix_markets_symbol");

                    b.ToTable("markets", (string)null);
                });

            modelBuilder.Entity("HVTradingBot.Infrastructure.Persistence.Entities.MarketSelectionEntity", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int>("AppliedVersion")
                        .HasColumnType("INTEGER")
                        .HasColumnName("applied_version");

                    b.Property<bool>("DerivedOnlyWhenForexClosed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true)
                        .HasColumnName("derived_only_when_forex_closed");

                    b.Property<string>("Instruments")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("instruments");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at_utc");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_by");

                    b.Property<int>("Version")
                        .HasColumnType("INTEGER")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_market_selection");

                    b.ToTable("market_selection", (string)null);
                });

            modelBuilder.Entity("HVTradingBot.Infrastructure.Persistence.Entities.MarketSnapshotEntity", b =>
                {
                    b.Property<string>("Instrument")
                        .HasColumnType("TEXT")
                        .HasColumnName("instrument");

                    b.Property<double>("Ask")
                        .HasPrecision(28, 10)
                        .HasColumnType("REAL")
                        .HasColumnName("ask");

                    b.Property<double>("Bid")
                        .HasPrecision(28, 10)
                        .HasColumnType("REAL")
                        .HasColumnName("bid");

                    b.Property<string>("Indicators")
                        .HasColumnType("TEXT")
                        .HasColumnName("indicators");

                    b.Property<string>("LastDecision")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_decision");

                    b.Property<DateTime?>("LastDecisionTimeUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_decision_time_utc");

                    b.Property<DateTime>("MarketTimeUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("market_time_utc");

                    b.Property<string>("Regime")
                        .HasColumnType("TEXT")
                        .HasColumnName("regime");

                    b.Property<double>("SpreadPips")
                        .HasPrecision(28, 10)
                        .HasColumnType("REAL")
                        .HasColumnName("spread_pips");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Instrument")
                        .HasName("pk_market_snapshots");

                    b.ToTable("market_snapshots", (string)null);
                });

            modelBuilder.Entity("HVTradingBot.Infrastructure.Persistence.Entities.NotificationSettingsEntity", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER")
                        .HasColumnName("enabled");

                    b.Property<string>("FromAddress")
                        .HasMaxLength(320)
                        .HasColumnType("TEXT")
                        .HasColumnName("from_address");

                    b.Property<string>("FromName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("from_name");

                    b.Property<bool?>("LastAttemptSucceeded")
                        .HasColumnType("INTEGER")
                        .HasColumnName("last_attempt_succeeded");

                    b.Property<DateTime?>("LastAttemptUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_attempt_utc");

                    b.Property<string>("LastError")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT")
                        .HasColumnName("last_error");

                    b.Property<bool>("OnKillSwitch")
                        .HasColumnType("INTEGER")
                        .HasColumnName("on_kill_switch");

                    b.Property<bool>("OnOrderRejected")
                        .HasColumnType("INTEGER")
                        .HasColumnName("on_order_rejected");

                    b.Property<bool>("OnTradeClosed")
                        .HasColumnType("INTEGER")
                        .HasColumnName("on_trade_closed");

                    b.Property<bool>("OnTradeOpened")
                        .HasColumnType("INTEGER")
                        .HasColumnName("on_trade_opened");

                    b.Property<string>("PasswordHint")
                        .HasMaxLength(8)
                        .HasColumnType("TEXT")
                        .HasColumnName("password_hint");

                    b.Property<string>("PasswordProtected")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT")
                        .HasColumnName("password_protected");

                    b.Property<string>("SmtpHost")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("smtp_host");

                    b.Property<int>("SmtpPort")
                        .HasColumnType("INTEGER")
                        .HasColumnName("smtp_port");

                    b.Property<string>("ToAddresses")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("to_addresses");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at_utc");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_by");

                    b.Property<string>("Username")
                        .HasMaxLength(320)
                        .HasColumnType("TEXT")
                        .HasColumnName("username");

                    b.Property<int>("Version")
                        .HasColumnType("INTEGER")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_notification_settings");

                    b.ToTable("notification_settings", (string)null);
                });

            modelBuilder.Entity("HVTradingBot.Infrastructure.Persistence.Entities.OrderEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("Broker")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("broker");

                    b.Property<string>("BrokerAccountId")
                        .HasColumnType("TEXT")
                        .HasColumnName("broker_account_id");

                    b.Property<string>("BrokerContractId")
                        .HasColumnType("TEXT")
                        .HasColumnName("broker_contract_id");

                    b.Property<string>("ClientOrderId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("client_order_id");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("correlation_id");

                    b.Property<Guid?>("DecisionId")
                        .HasColumnType("TEXT")
                        .HasColumnName("decision_id");

                    b.Property<string>("Direction")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("direction");

                    b.Property<double?>("FillPrice")
                        .HasPrecision(28, 10)
                        .HasColumnType("REAL")
                        .HasColumnName("fill_price");

                    b.Property<string>("Instrument")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("instrument");

                    b.Property<DateTime>("MarketTimeUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("market_time_utc");

                    b.Property<DateTime>("RecordedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("recorded_at_utc");

                    b.Property<string>("RejectReason")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT")
                        .HasColumnName("reject_reason");

                    b.Property<double>("RequestedPrice")
                        .HasPrecision(28, 10)
                        .HasColumnType("REAL")
                        .HasColumnName("requested_price");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.Property<double>("StopLoss")
                        .HasPrecision(28, 10)
                        .HasColumnType("REAL")
                        .HasColumnName("stop_loss");

                    b.Property<double>("TakeProfit")
                        .HasPrecision(28, 10)
                        .HasColumnType("REAL")
                        .HasColumnName("take_profit");

                    b.Property<double>("Units")
                        .HasPrecision(28, 10)
                        .HasColumnType("REAL")
                        .HasColumnName("units");

                    b.HasKey("Id")
                        .HasName("pk_orders");

                    b.HasIndex("BrokerContractId")
                        .HasDatabaseName("ix_orders_broker_contract_id");

                    b.HasIndex("ClientOrderId")
                        .IsUnique()
                        .HasDatabaseName("ix_orders_client_order_id");

                    b.ToTable("orders", (string)null);
                });

            modelBuilder.Entity("HVTradingBot.Infrastructure.Persistence.Entities.PaperAccountEntity", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<double>("Balance")
                        .HasPrecision(28, 10)
                        .HasColumnType("REAL")
                        .HasColumnName("balance");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("currency");

                    b.Property<double>("StartingBalance")
                        .HasPrecision(28, 10)
                        .HasColumnType("REAL")
                        .HasColumnName("starting_balance");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_paper_accounts");

                    b.ToTable("paper_accounts", (string)null);
                });

            modelBuilder.Entity("HVTradingBot.Infrastructure.Persistence.Entities.PositionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("Broker")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("broker");

                    b.Property<string>("BrokerAccountId")
                        .HasColumnType("TEXT")
                        .HasColumnName("broker_account_id");

                    b.Property<string>("BrokerContractId")
                        .HasColumnType("TEXT")
                        .HasColumnName("broker_contract_id");

                    b.Property<int?>("BrokerMultiplier")
                        .HasColumnType("INTEGER")
                        .HasColumnName("broker_multiplier");

                    b.Property<double?>("BrokerStake")
                        .HasPrecision(28, 10)
                        .HasColumnType("REAL")
                        .HasColumnName("broker_stake");

                    b.Property<string>("ClientOrderId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("client_order_id");

                    b.Property<DateTime?>("ClosedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("closed_at_utc");

                    b.Property<double?>("Commission")
                        .HasPrecision(28, 10)
                        .HasColumnType("REAL")
                        .HasColumnName("commission");

                    b.Property<string>("Direction")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("direction");

                    b.Property<double>("EntryPrice")
                        .HasPrecision(28, 10)
                        .HasColumnType("REAL")
                        .HasColumnName("entry_price");

                    b.Property<double?>("ExitPrice")
                        .HasPrecision(28, 10)
                        .HasColumnType("REAL")
                        .HasColumnName("exit_price");

                    b.Property<string>("ExitReason")
                        .HasColumnType("TEXT")
                        .HasColumnName("exit_reason");

                    b.Property<double>("InitialRiskAmount")
                        .HasPrecision(28, 10)
                        .HasColumnType("REAL")
                        .HasColumnName("initial_risk_amount");

                    b.Property<string>("Instrument")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("instrument");

                    b.Property<bool>("IsOpen")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_open");

                    b.Property<double?>("MaePips")
                        .HasPrecision(28, 10)
                        .HasColumnType("REAL")
                        .HasColumnName("mae_pips");

                    b.Property<double>("MaxAdverseExcursion")
                        .HasPrecision(28, 10)
                        .HasColumnType("REAL")
                        .HasColumnName("max_adverse_excursion");

                    b.Property<double>("MaxFavorableExcursion")
                        .HasPrecision(28, 10)
                        .HasColumnType("REAL")
                        .HasColumnName("max_favorable_excursion");

                    b.Property<double?>("MfePips")
                        .HasPrecision(28, 10)
                        .HasColumnType("REAL")
                        .HasColumnName("mfe_pips");

                    b.Property<DateTime>("OpenedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("opened_at_utc");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("TEXT")
                        .HasColumnName("order_id");

                    b.Property<double?>("RMultiple")
                        .HasPrecision(28, 10)
                        .HasColumnType("REAL")
                        .HasColumnName("r_multiple");

                    b.Property<double?>("RealizedPnl")
                        .HasPrecision(28, 10)
                        .HasColumnType("REAL")
                        .HasColumnName("realized_pnl");

                    b.Property<int>("Score")
                        .HasColumnType("INTEGER")
                        .HasColumnName("score");

                    b.Property<double>("StopLoss")
                        .HasPrecision(28, 10)
                        .HasColumnType("REAL")
                        .HasColumnName("stop_loss");

                    b.Property<string>("Strategy")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("strategy");

                    b.Property<double>("TakeProfit")
                        .HasPrecision(28, 10)
                        .HasColumnType("REAL")
                        .HasColumnName("take_profit");

                    b.Property<double>("Units")
                        .HasPrecision(28, 10)
                        .HasColumnType("REAL")
                        .HasColumnName("units");

                    b.HasKey("Id")
                        .HasName("pk_positions");

                    b.HasIndex("BrokerContractId")
                        .HasDatabaseName("ix_positions_broker_contract_id");

                    b.HasIndex("ClientOrderId")
                        .IsUnique()
                        .HasDatabaseName("ix_positions_client_order_id");

                    b.HasIndex("ClosedAtUtc")
                        .HasDatabaseName("ix_positions_closed_at_utc");

                    b.HasIndex("IsOpen")
                        .HasDatabaseName("ix_positions_is_open");

                    b.ToTable("positions", (string)null);
                });

            modelBuilder.Entity("HVTradingBot.Infrastructure.Persistence.Entities.RiskSettingsEntity", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Limits")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("limits");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at_utc");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_by");

                    b.Property<int>("Version")
                        .HasColumnType("INTEGER")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_risk_settings");

                    b.ToTable("risk_settings", (string)null);
                });

            modelBuilder.Entity("HVTradingBot.Infrastructure.Persistence.Entities.SetupOutcomeEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("AssetClass")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("asset_class");

                    b.Property<DateTime?>("ClosedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("closed_at_utc");

                    b.Property<Guid?>("DecisionId")
                        .HasColumnType("TEXT")
                        .HasColumnName("decision_id");

                    b.Property<string>("DecisionState")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("decision_state");

                    b.Property<string>("Direction")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("direction");

                    b.Property<double>("Entry")
                        .HasPrecision(28, 10)
                        .HasColumnType("REAL")
                        .HasColumnName("entry");

                    b.Property<double?>("ExitPrice")
                        .HasPrecision(28, 10)
                        .HasColumnType("REAL")
                        .HasColumnName("exit_price");

                    b.Property<string>("Instrument")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("instrument");

                    b.Property<DateTime>("OpenedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("opened_at_utc");

                    b.Property<double?>("RMultiple")
                        .HasPrecision(28, 10)
                        .HasColumnType("REAL")
                        .HasColumnName("r_multiple");

                    b.Property<string>("Regime")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("regime");

                    b.Property<int>("Score")
                        .HasColumnType("INTEGER")
                        .HasColumnName("score");

                    b.Property<string>("SetupId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("setup_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.Property<double>("StopLoss")
                        .HasPrecision(28, 10)
                        .HasColumnType("REAL")
                        .HasColumnName("stop_loss");

                    b.Property<string>("Strategy")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("strategy");

                    b.Property<double>("TakeProfit")
                        .HasPrecision(28, 10)
                        .HasColumnType("REAL")
                        .HasColumnName("take_profit");

                    b.HasKey("Id")
                        .HasName("pk_setup_outcomes");

                    b.HasIndex("ClosedAtUtc")
                        .HasDatabaseName("ix_setup_outcomes_closed_at_utc");

                    b.HasIndex("SetupId")
                        .IsUnique()
                        .HasDatabaseName("ix_setup_outcomes_setup_id");

                    b.HasIndex("Instrument", "Status")
                        .HasDatabaseName("ix_setup_outcomes_instrument_status");

                    b.ToTable("setup_outcomes", (string)null);
                });

            modelBuilder.Entity("HVTradingBot.Infrastructure.Persistence.Entities.SystemStateEntity", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("BrokerAccountId")
                        .HasColumnType("TEXT")
                        .HasColumnName("broker_account_id");

                    b.Property<bool>("BrokerIsDemo")
                        .HasColumnType("INTEGER")
                        .HasColumnName("broker_is_demo");

                    b.Property<string>("BrokerName")
                        .HasColumnType("TEXT")
                        .HasColumnName("broker_name");

                    b.Property<int>("ConsecutiveLosses")
                        .HasColumnType("INTEGER")
                        .HasColumnName("consecutive_losses");

                    b.Property<DateTime?>("CooldownUntilUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("cooldown_until_utc");

                    b.Property<double>("DailyRealizedPnl")
                        .HasPrecision(28, 10)
                        .HasColumnType("REAL")
                        .HasColumnName("daily_realized_pnl");

                    b.Property<double>("DerivedDailyRealizedPnl")
                        .HasPrecision(28, 10)
                        .HasColumnType("REAL")
                        .HasColumnName("derived_daily_realized_pnl");

                    b.Property<bool>("KillSwitchActive")
                        .HasColumnType("INTEGER")
                        .HasColumnName("kill_switch_active");

                    b.Property<DateTime?>("KillSwitchChangedUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("kill_switch_changed_utc");

                    b.Property<string>("KillSwitchReason")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT")
                        .HasColumnName("kill_switch_reason");

                    b.Property<DateTime?>("LastBarTimeUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_bar_time_utc");

                    b.Property<DateTime?>("LastDataReceivedUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_data_received_utc");

                    b.Property<string>("MarketDataSource")
                        .HasColumnType("TEXT")
                        .HasColumnName("market_data_source");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("mode");

                    b.Property<DateOnly?>("PnlDay")
                        .HasColumnType("TEXT")
                        .HasColumnName("pnl_day");

                    b.Property<DateOnly?>("PnlWeekStart")
                        .HasColumnType("TEXT")
                        .HasColumnName("pnl_week_start");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER")
                        .HasColumnName("version");

                    b.Property<double>("WeeklyRealizedPnl")
                        .HasPrecision(28, 10)
                        .HasColumnType("REAL")
                        .HasColumnName("weekly_realized_pnl");

                    b.Property<DateTime?>("WorkerHeartbeatUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("worker_heartbeat_utc");

                    b.HasKey("Id")
                        .HasName("pk_system_state");

                    b.ToTable("system_state", (string)null);
                });

            modelBuilder.Entity("HVTradingBot.Infrastructure.Persistence.Entities.TestTradeEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("ClientOrderId")
                        .HasColumnType("TEXT")
                        .HasColumnName("client_order_id");

                    b.Property<DateTime?>("CloseRequestedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("close_requested_at_utc");

                    b.Property<DateTime?>("ClosedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("closed_at_utc");

                    b.Property<double?>("ExitPrice")
                        .HasPrecision(28, 10)
                        .HasColumnType("REAL")
                        .HasColumnName("exit_price");

                    b.Property<double?>("FillPrice")
                        .HasPrecision(28, 10)
                        .HasColumnType("REAL")
                        .HasColumnName("fill_price");

                    b.Property<int>("HoldSeconds")
                        .HasColumnType("INTEGER")
                        .HasColumnName("hold_seconds");

                    b.Property<string>("Instrument")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasColumnName("instrument");

                    b.Property<string>("Message")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT")
                        .HasColumnName("message");

                    b.Property<DateTime?>("OpenedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("opened_at_utc");

                    b.Property<Guid?>("PositionId")
                        .HasColumnType("TEXT")
                        .HasColumnName("position_id");

                    b.Property<double?>("RealizedPnl")
                        .HasPrecision(28, 10)
                        .HasColumnType("REAL")
                        .HasColumnName("realized_pnl");

                    b.Property<DateTime>("RequestedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("requested_at_utc");

                    b.Property<string>("RequestedBy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("requested_by");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_test_trades");

                    b.HasIndex("RequestedAtUtc")
                        .HasDatabaseName("ix_test_trades_requested_at_utc");

                    b.ToTable("test_trades", (string)null);
                });

            modelBuilder.Entity("HVTradingBot.Infrastructure.Persistence.Entities.TradeDecisionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("ClientOrderId")
                        .HasColumnType("TEXT")
                        .HasColumnName("client_order_id");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("correlation_id");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("details");

                    b.Property<string>("Direction")
                        .HasColumnType("TEXT")
                        .HasColumnName("direction");

                    b.Property<double?>("Entry")
                        .HasPrecision(28, 10)
                        .HasColumnType("REAL")
                        .HasColumnName("entry");

                    b.Property<string>("Instrument")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("instrument");

                    b.Property<DateTime>("MarketTimeUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("market_time_utc");

                    b.Property<string>("Reasons")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT")
                        .HasColumnName("reasons");

                    b.Property<DateTime>("RecordedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("recorded_at_utc");

                    b.Property<string>("Regime")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("regime");

                    b.Property<double?>("RewardToRisk")
                        .HasPrecision(28, 10)
                        .HasColumnType("REAL")
                        .HasColumnName("reward_to_risk");

                    b.Property<int?>("Score")
                        .HasColumnType("INTEGER")
                        .HasColumnName("score");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("state");

                    b.Property<double?>("StopLoss")
                        .HasPrecision(28, 10)
                        .HasColumnType("REAL")
                        .HasColumnName("stop_loss");

                    b.Property<string>("Strategy")
                        .HasColumnType("TEXT")
                        .HasColumnName("strategy");

                    b.Property<double?>("TakeProfit")
                        .HasPrecision(28, 10)
                        .HasColumnType("REAL")
                        .HasColumnName("take_profit");

                    b.HasKey("Id")
                        .HasName("pk_trade_decisions");

                    b.HasIndex("ClientOrderId")
                        .HasDatabaseName("ix_trade_decisions_client_order_id");

                    b.HasIndex("MarketTimeUtc")
                        .HasDatabaseName("ix_trade_decisions_market_time_utc");

                    b.HasIndex("State")
                        .HasDatabaseName("ix_trade_decisions_state");

                    b.HasIndex("Instrument", "MarketTimeUtc")
                        .HasDatabaseName("ix_trade_decisions_instrument_market_time_utc");

                    b.ToTable("trade_decisions", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
