// <auto-generated />
using System;
using HVTradingBot.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HVTradingBot.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(TradingDbContext))]
    partial class TradingDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HVTradingBot.Infrastructure.Persistence.Entities.AuditLogEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("action");

                    b.Property<string>("Actor")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("actor");

                    b.Property<string>("CorrelationId")
                        .HasColumnType("text")
                        .HasColumnName("correlation_id");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("details");

                    b.Property<DateTime>("TimestampUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp_utc");

                    b.HasKey("Id")
                        .HasName("pk_audit_logs");

                    b.HasIndex("TimestampUtc")
                        .HasDatabaseName("ix_audit_logs_timestamp_utc");

                    b.ToTable("audit_logs", (string)null);
                });

            modelBuilder.Entity("HVTradingBot.Infrastructure.Persistence.Entities.BacktestRunEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<decimal>("NetPnl")
                        .HasPrecision(28, 10)
                        .HasColumnType("numeric(28,10)")
                        .HasColumnName("net_pnl");

                    b.Property<string>("Parameters")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("parameters");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("summary");

                    b.Property<int>("TotalTrades")
                        .HasColumnType("integer")
                        .HasColumnName("total_trades");

                    b.HasKey("Id")
                        .HasName("pk_backtest_runs");

                    b.HasIndex("CreatedAtUtc")
                        .HasDatabaseName("ix_backtest_runs_created_at_utc");

                    b.ToTable("backtest_runs", (string)null);
                });

            modelBuilder.Entity("HVTradingBot.Infrastructure.Persistence.Entities.BrokerAccountEntity", b =>
                {
                    b.Property<string>("AccountKey")
                        .HasColumnType("text")
                        .HasColumnName("account_key");

                    b.Property<string>("Broker")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("broker");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("currency");

                    b.Property<bool>("IsDemo")
                        .HasColumnType("boolean")
                        .HasColumnName("is_demo");

                    b.Property<decimal>("LastBalance")
                        .HasPrecision(28, 10)
                        .HasColumnType("numeric(28,10)")
                        .HasColumnName("last_balance");

                    b.Property<decimal>("StartingBalance")
                        .HasPrecision(28, 10)
                        .HasColumnType("numeric(28,10)")
                        .HasColumnName("starting_balance");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("AccountKey")
                        .HasName("pk_broker_accounts");

                    b.ToTable("broker_accounts", (string)null);
                });

            modelBuilder.Entity("HVTradingBot.Infrastructure.Persistence.Entities.BrokerConnectionStatusEntity", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<string>("AccountsJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("accounts_json");

                    b.Property<DateTime>("CheckedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("checked_at_utc");

                    b.Property<string>("ConnectedAccountId")
                        .HasColumnType("text")
                        .HasColumnName("connected_account_id");

                    b.Property<string>("Message")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("message");

                    b.Property<int>("SettingsVersion")
                        .HasColumnType("integer")
                        .HasColumnName("settings_version");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_broker_connection_status");

                    b.ToTable("broker_connection_status", (string)null);
                });

            modelBuilder.Entity("HVTradingBot.Infrastructure.Persistence.Entities.BrokerSettingsEntity", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<string>("DerivAccountId")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("deriv_account_id");

                    b.Property<string>("DerivApiTokenHint")
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("deriv_api_token_hint");

                    b.Property<string>("DerivApiTokenProtected")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("deriv_api_token_protected");

                    b.Property<string>("DerivAppId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("deriv_app_id");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("updated_by");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_broker_settings");

                    b.ToTable("broker_settings", (string)null);
                });

            modelBuilder.Entity("HVTradingBot.Infrastructure.Persistence.Entities.CandleEntity", b =>
                {
                    b.Property<string>("Instrument")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("instrument");

                    b.Property<string>("TimeFrame")
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("time_frame");

                    b.Property<DateTime>("OpenTimeUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("open_time_utc");

                    b.Property<decimal>("Close")
                        .HasPrecision(28, 10)
                        .HasColumnType("numeric(28,10)")
                        .HasColumnName("close");

                    b.Property<decimal>("High")
                        .HasPrecision(28, 10)
                        .HasColumnType("numeric(28,10)")
                        .HasColumnName("high");

                    b.Property<decimal>("Low")
                        .HasPrecision(28, 10)
                        .HasColumnType("numeric(28,10)")
                        .HasColumnName("low");

                    b.Property<decimal>("Open")
                        .HasPrecision(28, 10)
                        .HasColumnType("numeric(28,10)")
                        .HasColumnName("open");

                    b.Property<decimal>("Spread")
                        .HasPrecision(28, 10)
                        .HasColumnType("numeric(28,10)")
                        .HasColumnName("spread");

                    b.Property<long>("Volume")
                        .HasColumnType("bigint")
                        .HasColumnName("volume");

                    b.HasKey("Instrument", "TimeFrame", "OpenTimeUtc")
                        .HasName("pk_candles");

                    b.ToTable("candles", (string)null);
                });

            modelBuilder.Entity("HVTradingBot.Infrastructure.Persistence.Entities.MarketEntity", b =>
                {
                    b.Property<string>("BrokerSymbol")
                        .HasColumnType("text")
                        .HasColumnName("broker_symbol");

                    b.Property<string>("AssetClass")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("asset_class");

                    b.Property<string>("BaseCurrency")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("base_currency");

                    b.Property<bool>("IsOpen")
                        .HasColumnType("boolean")
                        .HasColumnName("is_open");

                    b.Property<bool>("IsTradable")
                        .HasColumnType("boolean")
                        .HasColumnName("is_tradable");

                    b.Property<string>("Market")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("market");

                    b.Property<string>("Multipliers")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("multipliers");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<decimal>("PipSize")
                        .HasPrecision(28, 10)
                        .HasColumnType("numeric(28,10)")
                        .HasColumnName("pip_size");

                    b.Property<int>("PriceDecimals")
                        .HasColumnType("integer")
                        .HasColumnName("price_decimals");

                    b.Property<string>("QuoteCurrency")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("quote_currency");

                    b.Property<string>("Submarket")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("submarket");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("symbol");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("BrokerSymbol")
                        .HasName("pk_markets");

                    b.HasIndex("Symbol")
                        .IsUnique()
                        .HasDatabaseName("ix_markets_symbol");

                    b.ToTable("markets", (string)null);
                });

            modelBuilder.Entity("HVTradingBot.Infrastructure.Persistence.Entities.MarketSelectionEntity", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<int>("AppliedVersion")
                        .HasColumnType("integer")
                        .HasColumnName("applied_version");

                    b.Property<string>("Instruments")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("instruments");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_market_selection");

                    b.ToTable("market_selection", (string)null);
                });

            modelBuilder.Entity("HVTradingBot.Infrastructure.Persistence.Entities.MarketSnapshotEntity", b =>
                {
                    b.Property<string>("Instrument")
                        .HasColumnType("text")
                        .HasColumnName("instrument");

                    b.Property<decimal>("Ask")
                        .HasPrecision(28, 10)
                        .HasColumnType("numeric(28,10)")
                        .HasColumnName("ask");

                    b.Property<decimal>("Bid")
                        .HasPrecision(28, 10)
                        .HasColumnType("numeric(28,10)")
                        .HasColumnName("bid");

                    b.Property<string>("Indicators")
                        .HasColumnType("jsonb")
                        .HasColumnName("indicators");

                    b.Property<string>("LastDecision")
                        .HasColumnType("text")
                        .HasColumnName("last_decision");

                    b.Property<DateTime?>("LastDecisionTimeUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_decision_time_utc");

                    b.Property<DateTime>("MarketTimeUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("market_time_utc");

                    b.Property<string>("Regime")
                        .HasColumnType("text")
                        .HasColumnName("regime");

                    b.Property<decimal>("SpreadPips")
                        .HasPrecision(28, 10)
                        .HasColumnType("numeric(28,10)")
                        .HasColumnName("spread_pips");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Instrument")
                        .HasName("pk_market_snapshots");

                    b.ToTable("market_snapshots", (string)null);
                });

            modelBuilder.Entity("HVTradingBot.Infrastructure.Persistence.Entities.OrderEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Broker")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("broker");

                    b.Property<string>("BrokerAccountId")
                        .HasColumnType("text")
                        .HasColumnName("broker_account_id");

                    b.Property<string>("BrokerContractId")
                        .HasColumnType("text")
                        .HasColumnName("broker_contract_id");

                    b.Property<string>("ClientOrderId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("client_order_id");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("correlation_id");

                    b.Property<Guid?>("DecisionId")
                        .HasColumnType("uuid")
                        .HasColumnName("decision_id");

                    b.Property<string>("Direction")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("direction");

                    b.Property<decimal?>("FillPrice")
                        .HasPrecision(28, 10)
                        .HasColumnType("numeric(28,10)")
                        .HasColumnName("fill_price");

                    b.Property<string>("Instrument")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("instrument");

                    b.Property<DateTime>("MarketTimeUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("market_time_utc");

                    b.Property<DateTime>("RecordedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("recorded_at_utc");

                    b.Property<string>("RejectReason")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("reject_reason");

                    b.Property<decimal>("RequestedPrice")
                        .HasPrecision(28, 10)
                        .HasColumnType("numeric(28,10)")
                        .HasColumnName("requested_price");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<decimal>("StopLoss")
                        .HasPrecision(28, 10)
                        .HasColumnType("numeric(28,10)")
                        .HasColumnName("stop_loss");

                    b.Property<decimal>("TakeProfit")
                        .HasPrecision(28, 10)
                        .HasColumnType("numeric(28,10)")
                        .HasColumnName("take_profit");

                    b.Property<decimal>("Units")
                        .HasPrecision(28, 10)
                        .HasColumnType("numeric(28,10)")
                        .HasColumnName("units");

                    b.HasKey("Id")
                        .HasName("pk_orders");

                    b.HasIndex("BrokerContractId")
                        .HasDatabaseName("ix_orders_broker_contract_id");

                    b.HasIndex("ClientOrderId")
                        .IsUnique()
                        .HasDatabaseName("ix_orders_client_order_id");

                    b.ToTable("orders", (string)null);
                });

            modelBuilder.Entity("HVTradingBot.Infrastructure.Persistence.Entities.PaperAccountEntity", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<decimal>("Balance")
                        .HasPrecision(28, 10)
                        .HasColumnType("numeric(28,10)")
                        .HasColumnName("balance");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("currency");

                    b.Property<decimal>("StartingBalance")
                        .HasPrecision(28, 10)
                        .HasColumnType("numeric(28,10)")
                        .HasColumnName("starting_balance");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_paper_accounts");

                    b.ToTable("paper_accounts", (string)null);
                });

            modelBuilder.Entity("HVTradingBot.Infrastructure.Persistence.Entities.PositionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Broker")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("broker");

                    b.Property<string>("BrokerAccountId")
                        .HasColumnType("text")
                        .HasColumnName("broker_account_id");

                    b.Property<string>("BrokerContractId")
                        .HasColumnType("text")
                        .HasColumnName("broker_contract_id");

                    b.Property<int?>("BrokerMultiplier")
                        .HasColumnType("integer")
                        .HasColumnName("broker_multiplier");

                    b.Property<decimal?>("BrokerStake")
                        .HasPrecision(28, 10)
                        .HasColumnType("numeric(28,10)")
                        .HasColumnName("broker_stake");

                    b.Property<string>("ClientOrderId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("client_order_id");

                    b.Property<DateTime?>("ClosedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("closed_at_utc");

                    b.Property<string>("Direction")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("direction");

                    b.Property<decimal>("EntryPrice")
                        .HasPrecision(28, 10)
                        .HasColumnType("numeric(28,10)")
                        .HasColumnName("entry_price");

                    b.Property<decimal?>("ExitPrice")
                        .HasPrecision(28, 10)
                        .HasColumnType("numeric(28,10)")
                        .HasColumnName("exit_price");

                    b.Property<string>("ExitReason")
                        .HasColumnType("text")
                        .HasColumnName("exit_reason");

                    b.Property<decimal>("InitialRiskAmount")
                        .HasPrecision(28, 10)
                        .HasColumnType("numeric(28,10)")
                        .HasColumnName("initial_risk_amount");

                    b.Property<string>("Instrument")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("instrument");

                    b.Property<bool>("IsOpen")
                        .HasColumnType("boolean")
                        .HasColumnName("is_open");

                    b.Property<decimal?>("MaePips")
                        .HasPrecision(28, 10)
                        .HasColumnType("numeric(28,10)")
                        .HasColumnName("mae_pips");

                    b.Property<decimal>("MaxAdverseExcursion")
                        .HasPrecision(28, 10)
                        .HasColumnType("numeric(28,10)")
                        .HasColumnName("max_adverse_excursion");

                    b.Property<decimal>("MaxFavorableExcursion")
                        .HasPrecision(28, 10)
                        .HasColumnType("numeric(28,10)")
                        .HasColumnName("max_favorable_excursion");

                    b.Property<decimal?>("MfePips")
                        .HasPrecision(28, 10)
                        .HasColumnType("numeric(28,10)")
                        .HasColumnName("mfe_pips");

                    b.Property<DateTime>("OpenedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("opened_at_utc");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("order_id");

                    b.Property<decimal?>("RMultiple")
                        .HasPrecision(28, 10)
                        .HasColumnType("numeric(28,10)")
                        .HasColumnName("r_multiple");

                    b.Property<decimal?>("RealizedPnl")
                        .HasPrecision(28, 10)
                        .HasColumnType("numeric(28,10)")
                        .HasColumnName("realized_pnl");

                    b.Property<int>("Score")
                        .HasColumnType("integer")
                        .HasColumnName("score");

                    b.Property<decimal>("StopLoss")
                        .HasPrecision(28, 10)
                        .HasColumnType("numeric(28,10)")
                        .HasColumnName("stop_loss");

                    b.Property<string>("Strategy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("strategy");

                    b.Property<decimal>("TakeProfit")
                        .HasPrecision(28, 10)
                        .HasColumnType("numeric(28,10)")
                        .HasColumnName("take_profit");

                    b.Property<decimal>("Units")
                        .HasPrecision(28, 10)
                        .HasColumnType("numeric(28,10)")
                        .HasColumnName("units");

                    b.HasKey("Id")
                        .HasName("pk_positions");

                    b.HasIndex("BrokerContractId")
                        .HasDatabaseName("ix_positions_broker_contract_id");

                    b.HasIndex("ClientOrderId")
                        .IsUnique()
                        .HasDatabaseName("ix_positions_client_order_id");

                    b.HasIndex("ClosedAtUtc")
                        .HasDatabaseName("ix_positions_closed_at_utc");

                    b.HasIndex("IsOpen")
                        .HasDatabaseName("ix_positions_is_open");

                    b.ToTable("positions", (string)null);
                });

            modelBuilder.Entity("HVTradingBot.Infrastructure.Persistence.Entities.SetupOutcomeEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AssetClass")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("asset_class");

                    b.Property<DateTime?>("ClosedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("closed_at_utc");

                    b.Property<Guid?>("DecisionId")
                        .HasColumnType("uuid")
                        .HasColumnName("decision_id");

                    b.Property<string>("DecisionState")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("decision_state");

                    b.Property<string>("Direction")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("direction");

                    b.Property<decimal>("Entry")
                        .HasPrecision(28, 10)
                        .HasColumnType("numeric(28,10)")
                        .HasColumnName("entry");

                    b.Property<decimal?>("ExitPrice")
                        .HasPrecision(28, 10)
                        .HasColumnType("numeric(28,10)")
                        .HasColumnName("exit_price");

                    b.Property<string>("Instrument")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("instrument");

                    b.Property<DateTime>("OpenedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("opened_at_utc");

                    b.Property<decimal?>("RMultiple")
                        .HasPrecision(28, 10)
                        .HasColumnType("numeric(28,10)")
                        .HasColumnName("r_multiple");

                    b.Property<string>("Regime")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("regime");

                    b.Property<int>("Score")
                        .HasColumnType("integer")
                        .HasColumnName("score");

                    b.Property<string>("SetupId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("setup_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<decimal>("StopLoss")
                        .HasPrecision(28, 10)
                        .HasColumnType("numeric(28,10)")
                        .HasColumnName("stop_loss");

                    b.Property<string>("Strategy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("strategy");

                    b.Property<decimal>("TakeProfit")
                        .HasPrecision(28, 10)
                        .HasColumnType("numeric(28,10)")
                        .HasColumnName("take_profit");

                    b.HasKey("Id")
                        .HasName("pk_setup_outcomes");

                    b.HasIndex("ClosedAtUtc")
                        .HasDatabaseName("ix_setup_outcomes_closed_at_utc");

                    b.HasIndex("SetupId")
                        .IsUnique()
                        .HasDatabaseName("ix_setup_outcomes_setup_id");

                    b.HasIndex("Instrument", "Status")
                        .HasDatabaseName("ix_setup_outcomes_instrument_status");

                    b.ToTable("setup_outcomes", (string)null);
                });

            modelBuilder.Entity("HVTradingBot.Infrastructure.Persistence.Entities.SystemStateEntity", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<string>("BrokerAccountId")
                        .HasColumnType("text")
                        .HasColumnName("broker_account_id");

                    b.Property<bool>("BrokerIsDemo")
                        .HasColumnType("boolean")
                        .HasColumnName("broker_is_demo");

                    b.Property<string>("BrokerName")
                        .HasColumnType("text")
                        .HasColumnName("broker_name");

                    b.Property<int>("ConsecutiveLosses")
                        .HasColumnType("integer")
                        .HasColumnName("consecutive_losses");

                    b.Property<DateTime?>("CooldownUntilUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cooldown_until_utc");

                    b.Property<decimal>("DailyRealizedPnl")
                        .HasPrecision(28, 10)
                        .HasColumnType("numeric(28,10)")
                        .HasColumnName("daily_realized_pnl");

                    b.Property<bool>("KillSwitchActive")
                        .HasColumnType("boolean")
                        .HasColumnName("kill_switch_active");

                    b.Property<DateTime?>("KillSwitchChangedUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("kill_switch_changed_utc");

                    b.Property<string>("KillSwitchReason")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("kill_switch_reason");

                    b.Property<DateTime?>("LastBarTimeUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_bar_time_utc");

                    b.Property<DateTime?>("LastDataReceivedUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_data_received_utc");

                    b.Property<string>("MarketDataSource")
                        .HasColumnType("text")
                        .HasColumnName("market_data_source");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("mode");

                    b.Property<DateOnly?>("PnlDay")
                        .HasColumnType("date")
                        .HasColumnName("pnl_day");

                    b.Property<DateOnly?>("PnlWeekStart")
                        .HasColumnType("date")
                        .HasColumnName("pnl_week_start");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<decimal>("WeeklyRealizedPnl")
                        .HasPrecision(28, 10)
                        .HasColumnType("numeric(28,10)")
                        .HasColumnName("weekly_realized_pnl");

                    b.Property<DateTime?>("WorkerHeartbeatUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("worker_heartbeat_utc");

                    b.HasKey("Id")
                        .HasName("pk_system_state");

                    b.ToTable("system_state", (string)null);
                });

            modelBuilder.Entity("HVTradingBot.Infrastructure.Persistence.Entities.TradeDecisionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ClientOrderId")
                        .HasColumnType("text")
                        .HasColumnName("client_order_id");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("correlation_id");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("details");

                    b.Property<string>("Direction")
                        .HasColumnType("text")
                        .HasColumnName("direction");

                    b.Property<decimal?>("Entry")
                        .HasPrecision(28, 10)
                        .HasColumnType("numeric(28,10)")
                        .HasColumnName("entry");

                    b.Property<string>("Instrument")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("instrument");

                    b.Property<DateTime>("MarketTimeUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("market_time_utc");

                    b.Property<string>("Reasons")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("reasons");

                    b.Property<DateTime>("RecordedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("recorded_at_utc");

                    b.Property<string>("Regime")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("regime");

                    b.Property<decimal?>("RewardToRisk")
                        .HasPrecision(28, 10)
                        .HasColumnType("numeric(28,10)")
                        .HasColumnName("reward_to_risk");

                    b.Property<int?>("Score")
                        .HasColumnType("integer")
                        .HasColumnName("score");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("state");

                    b.Property<decimal?>("StopLoss")
                        .HasPrecision(28, 10)
                        .HasColumnType("numeric(28,10)")
                        .HasColumnName("stop_loss");

                    b.Property<string>("Strategy")
                        .HasColumnType("text")
                        .HasColumnName("strategy");

                    b.Property<decimal?>("TakeProfit")
                        .HasPrecision(28, 10)
                        .HasColumnType("numeric(28,10)")
                        .HasColumnName("take_profit");

                    b.HasKey("Id")
                        .HasName("pk_trade_decisions");

                    b.HasIndex("ClientOrderId")
                        .HasDatabaseName("ix_trade_decisions_client_order_id");

                    b.HasIndex("MarketTimeUtc")
                        .HasDatabaseName("ix_trade_decisions_market_time_utc");

                    b.HasIndex("State")
                        .HasDatabaseName("ix_trade_decisions_state");

                    b.HasIndex("Instrument", "MarketTimeUtc")
                        .HasDatabaseName("ix_trade_decisions_instrument_market_time_utc");

                    b.ToTable("trade_decisions", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
